spring:
  datasource:
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
    driver-class-name: ${sky.datasource.driver-class-name}

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: hospital
    username: root
    password: "123456"
  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    accessKeyId: LTAI5t8vS5ruMyzGFf9usYhe
    accessKeySecret: r01mTvcwbmZ4WS2SZKSadwvi5TB8ZJ
    bucketName: szdxhzau

  redis:
    host: localhost
    port: 6379
    database: 10
